#!/usr/bin/env bash
# Run through mise run configure:envrc; credentials are never echoed.
set -euo pipefail
set +x
umask 077

repo_root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
target="$repo_root/.envrc"
if [[ -e "$target" || -L "$target" ]]; then
  printf 'A .envrc already exists; kept it unchanged. Edit it or move it before rerunning.\n' >&2
  exit 1
fi

printf 'Enter provider credentials and edition IDs from your accounts.\n'
printf 'CSB is needed for the next verification step. Other editions and Crossway can be left blank for now.\n'

prompt() {
  local name="$1" label="$2" required="$3" hidden="$4" value
  while true; do
    printf '%s: ' "$label" >&2
    if [[ "$hidden" == yes ]]; then
      IFS= read -r -s value || { printf '\nCancelled; no .envrc written.\n' >&2; exit 1; }
      printf '\n' >&2
    else
      IFS= read -r value || { printf '\nCancelled; no .envrc written.\n' >&2; exit 1; }
    fi
    if [[ "$required" == yes && -z "$value" ]]; then
      printf 'This value is required for CSB verification.\n' >&2
      continue
    fi
    # Bash %q quotes shell metacharacters; never evaluate user input.
    printf -v "$name" '%s' "$value"
    break
  done
}

prompt api_key 'API.Bible API key (hidden)' yes yes
prompt csb_id 'API.Bible CSB edition ID' yes no
prompt niv_id 'API.Bible NIV edition ID (optional)' no no
prompt nlt_id 'API.Bible NLT edition ID (optional)' no no
prompt crossway_key 'Crossway ESV API key (hidden, optional)' no yes

# Create only after all prompts finish; noclobber also protects against a race.
set -o noclobber
{
  printf '# Local server credentials. Generated by scripts/configure-envrc.sh.\n'
  printf '# Review this file, then run direnv allow.\n'
  printf 'export API_BIBLE_KEY=%q\n' "$api_key"
  printf 'export API_BIBLE_CSB_ID=%q\n' "$csb_id"
  printf 'export API_BIBLE_NIV_ID=%q\n' "$niv_id"
  printf 'export API_BIBLE_NLT_ID=%q\n' "$nlt_id"
  printf 'export CROSSWAY_KEY=%q\n' "$crossway_key"
} > "$target"
printf 'Created .envrc with owner-only permissions. Run direnv allow from the repository.\n'
